language: ruby
rvm:
- 2.1.1
bundler_args: --without kitchen_vagrant
before_install:
- echo -n $EC2_SSH_KEY_CHUNK_{0..25} >> ~/.ssh/id_ec2.base64
- cat ~/.ssh/id_ec2.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_ec2
- gem install bundler --pre
script:
- bundle exec rake travis
after_script:
- bundle exec kitchen destroy
env:
  global:
  - EC2_SSH_KEY_PATH="$HOME/.ssh/id_ec2"
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: cvRi4LMngHNN6mJTNUhHWuiNDr3sFHvfnNSF7/tS3kxcJAUTrLg4MY+RCYcF8pIvBPoeQPAHgScjcMwPXWTBNstHwbX2KzMnRSgAVXLNpxyT96qC715PoVK5GQdtxMNQkZ80LkEPDNMupmp+Ns/CHh+Jt8vMCY1QSkEUnXiKqBQ=
  - secure: l2HUBkfMH0zwbtxM6N8xW8tdB2IjQhi8eMPlfwLiZXocUKvGf4rftz2OWqQNoFJS9hgoIejtedVXPI2k/8whmnrll78oztrNqg5g58AWQrxHC1OTKBSafQI5KYf/t51UABpxOpV8/c9QPCs5IFA4G1pZUFT9Tcz2keneGOGv5Zk=
  - secure: KLHadkwXDBum1q0KW8qYDQj2exYmreYADA0THIvhEIMN2TTJ2PFczrBd+2rD9/Pgoa5TIw3xZ3dRtzs3Aqn0HSZMtcDGg//XCGyvIF0GV7s+CcNVl0obxpfolDhSFnkJYqjIq46dTq4WvzIpTOdX2iosbRt0VyZKbcyfd/Ph4Rk=
  - secure: IyzRU2NnWOretNXbI9G6MC4Jty2LHO14yd38dpp2Vzn+/j6zXD1LGzWkUFJKCYgqvXNj4f0fS3I5qNtI85i419c4FblojqSMdqNgy/1Z2ACdROCRfcujHcKYdeIqbQdMAVbQzoKUPngOzISmulHBs+H0jNek2VddB6BwB5tdORA=
  - secure: hkJ+QrtNUv/3a0qLVcBKmnTLU9SiVqHvOzUwekzjTTsPPzDHrM3K0HvsNQbkkijt/14aKzhXIfh41jIRu6oO4sqWQ5yC1gdHISgSrRcrokgk4hdGKfg+Iau4Y7BDQJFOUXyduqFXT2qQ5U27bX+qO1PsU9JvGKVZSkLIDzARrsQ=
  - secure: dAZqYZ36sqU+ayYrh41QO/JUJmrAAnENssntkKSspH2meAwA+KL4pzvhUKecEoV6YFd7QRFDn+V45iZck+FGHyB9SVgeCTARbTOjOWNPxuu2HMmh2rUAFJ6cJnGRdEti3lYRdvzCuasVdmZ27v+3ab7B6gM6KvIBpT49jVwqw68=
  - secure: YaRgtI+WgJEaVm9JaQA4bY80J+yRa4ZN5YuIuPbxc1uM4HtsSfEZ3jm0AM4RTi/f45wNlLDZP9djFU3vny4pAD3zUHOFCSpTyCD7zTGetGHgC2mgcoMwrZmbTJcMtIOgRJj/U7I1OwLfV8hL85/F8gjDIwP7XA5OYb3I9aDmojU=
  - secure: G8aziPrZEBosC1z/Taf9G/6R5Pj1XY11OcFUS0dYkjmYrsBVxxVR8jKv+l0ru29mjQwzmr6il3FE5BYTjaISIzJU39QPFSmFh092r2yYpvxtbiV/8C9qcyJ1wawFp3sfkP0jxARe3zVgmSPcXCJ5vkzTlapZwk+4W/+Dqg41h/M=
  - secure: Tq0QEhBJSUXfZGmzocJaXYetU749x2Xh3XuPc00QYceh6yWD4z+ukxQE9uoGpsOa6DEHAUUMC4Vc777VgVmuSTiQgRgtVO320KC1307fMle4ispRXjPb21Rdo43c6S5XRjsxOT5Slazo7UNLKLEVEAGQ/7e38+DNI1AIKlH5Zy4=
  - secure: O/FfEiQ09z03QfVKTRnuN8JT5PAYHTtDUaqOn+kEqkxRiQpZkrclH8ainfBsmqWQ6UfAE9IEDnRge2hlnnFmglLDofzfkr/DsAvQokybT3K0PH/mTLNovkStSm8TURKlgPQIbmv5kbxLAxAsItdUtgncNgJJUPYbicz64d1ty44=
  - secure: MTviSsP4PmLD6jb6rAYKp9jtU8zu5XAebmjLiBaVr7/93CIZ/5hxdjQitg/Npeocg7K+F+NbHvh5CP7ntQj5NL0d2ofJDIuzvXV1sAjsDuVayDwZmWtG0P1Sv06u9RO2dA9AngmnYE32UjEytxWqQU9pTUqN9L4J2iPTXZG43bE=
  - secure: C+EhiYxppBLsXBwhLNBtMdmXcwvhpxCpmo+MfnWzcvJwQz/YvZBa0u7CuNnQC61NvOhNeAS72UuABvREpCsIWh/BRHe6oBoljOPpG6YbxtUNaDM5A0dB20WHlI673TtDmg0pLKT7afrfFCyY9WgwfI6m0i3GNXMsyBFyEEUMGFI=
  - secure: WSaVhLW6w1qVdAUBDcdGJC3qrE2pYLtYoxzZbnF6gvOflXSoGgwv1MAZMF6cdSx91KfjsRIAmk6P1nIfWFZnUF0joYBXnfFGSMRWY6H26ZSBLmGpKsC/CI9H8hwpiq6NZe5GQWhpqkOfprCNqiRuCd/wsyyqQ2i9EGIXQnzfkJ4=
  - secure: GBBAWGgFmoW/htYIdd8QE729ELXCLbfJHp1vXXaVATcx3ugjUovD8Hbt0uJucUUo/7ue3Rf27duPwKikBuL5elI8/eLmF4Nvh9M/q8TnGXtxaVP3rLCdlxrB6EoiSJjYHp4LJZq2uzySjT0Ma5GJJmoepO/xR9MJQRkFYDOnoI8=
  - secure: ap/4tAQrBpMn0YCN12Y9jlfRVnzQJbpoIOiXwZq5WMDWIPKrgqn1vTO3FwgUMltbqZGnP2kOHsIUZcJAMAuuG99PqXN99cWMB0aG2JlxTEqjTA0d/O6pwDcIErMvfeKdJHSDpHZ0m3yB7LKgaNfRkYTLT/6vJDeWPCD/lyKGAjs=
  - secure: LdYYSnFqNwB40qP5U2RTdYSU8ylVOf774t3Z1b0E4T/FKtMgOblTlahFsZN+57/U07U/UyOffEkHaTlEo4U9HYSEp+hrkOeEAiOYzZXk02ece1LWXTjBZxLvLbY0NxAZzWZTwVnhE5AysfbUTt1QmmOc0bMq/E7ywiyJTk4n/nM=
  - secure: I5DB6xM6DNsMW4KliWMQfTTFasT6FQRlpWTkgHX7dB25mJsoYwcGqJ2xNtS1gsVYs9vz7AADu6DCV71yge0LmqnTufVB7yAJ/m6PDIyeW5V4ujVmRbSOoS9RpCptXxFWpQ4fOdqSvEOQjP0AyIlOm3WWJOBOAXvwvzYEgO8JcPA=
  - secure: Qkz9lbYB4YLscVUk2pWFIKz1bXEkXnWdtld+WPs5qksZtzqA3PGqa7pVkQ5f7481DuWuqqGduZCXYEsLYwUU16e+FyNAzNhohorbCeB0AfzpzMBO1nRgHupP/qeH0C+jIKsRFTjNR9enAP1gv5qbwEgoKXslnWa74UsY83V0R9E=
  - secure: Ep4ZsVoJR0s8OD5x44Y1MsrfjMhLgsn/iNEbTEsgtmDVVz6FfGM7vXUy7HKIWwQVX+dAln7RgE8Pb7gFk3kgUVVJBeoo83DHPoUzEQptr5sBKIsz3txj/42f80fkHS0Vcj3DusuWBTLITzq/JSZpJj8wwxRDeEG/74Qd4vyHjnI=
  - secure: UqNJnBtjxi+wsrBl0XpXrDeEewuadGrEiSb6IiRHRl4AUvTccNtaBHSAvakAF6A1lRLZmlXQWv7MXtZT9PkqKT4FFSbUT5rNmeN1pN0PxSjVSTGUOSskqmcfi+0QaW4b78Rz/MShSiS7Q37Y3/mfQIrY6a9uvtpHHgTAae2jzQI=
  - secure: b7AMxft2wL4USqhsdks17rce7pO2ZfZRY/Wjhv0fUVI05jzunMygWuaK2FhQyaZY79hktuE2do8kC4Hi9LxAKvIRNJuIbUybCiisQmhFduidyKfpbe+tW/FdzDpzzTfwiMwyUfVFqxeqKVUCcZYsvbEZ8ITGnLtkxaJ6A9aGSy4=
  - secure: YCOVUyepUFR9VbZVzDfVd/l1H1j6UmgWsfzVrHUkhRhkAElp/eeCJocp3QEEn+zhXgt9+ADXroetcg+syx4p0l+0JF7CDj1ipnNhgGMLWTS3FHYCV62aEZru5sazPdJ3b5lMCeSB4hXxGDjIhsgIETOKCbMK3PPin0HPfgJ2bns=
  - secure: B2JbkJgPbRTgEOkkbW1q6ffwx46LQRDZRhLJAXzetYLjv+Rnc6TUpwRJMN3TnGbIC1lNRfpl9EQlceWYj5gVzF7j8eOLgs3py8QWYiW5zAXLDieT/zagy0zHsP1CTqRUIByvq+LunfYWfDdEBiE3Xympogs/9l1Ef1dS3vCaETc=
  - secure: JiXDAO6nWra3YbMJV6DcfEvJNqylOP8ZZo1TqaREQvOSxdYbhGTDX0uQa7AEi0UuZM76MlMeYWRdh0zed6e+HYNxjqdwJ2x6Jci1+Op3F9vATU+IWvoDoTDB8Y0hv8bXYK9q61fj6QbtxEno5Mr8QFY8NUqsXKOoemdU06JOXE8=
  - secure: Q1o3bldTCvTp/tQ84jnL4iASt0iv3ooOF4uinadCVPRLWSEh/3p63Ku2lKyBY1WQ06pMV2rTWbPZrmWa4m7p/clfDxSFqZEcE7On+f3lW8UVD58oqhOhzrdzHfvPRiunm3d0A5jJl0qD/5LEmrsbH3yDjhAmeml/qzcN28g9OXY=
  - secure: BN+g8wO2DhhF4yshfC4qKUPvzayXX5YWBiteoHly8zgn0/r6iICFufmqOexiTasDiMiFoMv0WzccEyNnIqTzkMjIoCVJUA1K806yWbeUf7le6bNckRI93vsoQxtMmv3HTfwMMdUTeE2WlRiwuSq+lkLlxNmX6mwvfMagwrakTWM=
  - secure: ODt4cGKtgbXiAJ0yh2/Jr7TcbM5YdTH8TytDY2hmeXBjxwz9tN+DdcIIxf1OTq1or4mALTTt/2ATOvTNK5qP+pWB0R1pmMImeDZmLfOu89rcWH6xt3j8oicOXrObDfXXmNqdGVe7L4g/Sy2OxaBJsvX1EeYBmWGNiy0UsEvYnXI=
  - secure: XOXPZvrcdvvAMEpdvskGUcOXZUt/l9HYXXMpbQ0B4YvLgSHBhOw/vW/d+kP2osVXH9SC/un0Mc0k7/8kHs1TRUd/pD+FDIMDWw/mCoL3JZC1tp7cg/IR2KwNBYv2D/0B+gtm73OM/bZRXDQQmvDBf+9voIXrwe/Mm2R/f4zjzko=
  - secure: eGczGm0btQr0sg+rj6GP5VPy22nekiNh46PIp/onkKdZDWLXVF33SLBRk5krTtrJsrjhcKPsJ4e4/wUNPVQ/GIXeY250dOsFWgZBH31akFQsZfG6EJbMc2nTdJGKc0nqIIhdC6G1i06JYe3+nX1hm6aIWO5XYTbd702wMtubbe0=
  - secure: dOc+T/d/EvKuhjrEZPJmBmz4rv/zeMLPpLBBz5u3FfbZucVb9ANU3invmi9UGeedDVG5pBazv+RX9LB58f8Kc5ZJ8gAsfn6evNANp8i7iRS2qZLqUt2TbSdtwWflDSiL8reiyoYeXuhHdLyaHEZA7Nqj+B1CAarVuhKzUzb1coY=
  - secure: c3DduS6BatIoHyKqD9F6WaKGF1dE0qd8P2JSOK7HB6vVWEYGK1RpeTx3ljF14VLqSw6BLayZLjomuJYA9h718B/Kgp/TaV3Y5+0ea3ujZ6FklEGZVg7cfmB8qXsm75Ju+7ivT+1qZs5j504I7jKFlYFFcMjBvEOTeHn5rhQKtbA=
  matrix:
  - KITCHEN_INSTANCE="default-ubuntu-1204"
notifications:
  email:
  - techops@americanhonors.org
